### ISSUE TITLE
请问1.19和1.18的版本可以分享一下吗？

### ISSUE THREAD

**Issue by trockxi** [lework/kainstall-offline#1]
请问1.19和1.18的版本可以分享一下吗？听说1.20和1.21只支持containerd或CRI-O，不支持docker了，需要旧版本进行部署。

**Comment by lework** [comment]
最近调整了kainstall脚本和离线包存储的位置，只生成了最近的两个版本离线包，后续会生成所有的更新版本。另外k8s目前说明在1.20以后的版本**不推荐**使用docker作为运行时，且在未来的版本会去除这个选项，可能在1.23版本中去掉。所以使用1.20和1.21目前没啥问题。

**Comment by trockxi** [comment]
> 最近调整了kainstall脚本和离线包存储的位置，只生成了最近的两个版本离线包，后续会生成所有的更新版本。另外k8s目前说明在1.20以后的版本**不推荐**使用docker作为运行时，且在未来的版本会去除这个选项，可能在1.23版本中去掉。所以使用1.20和1.21目前没啥问题。

感激回复。
