### ISSUE TITLE
这要怎么破?

### ISSUE THREAD

**Issue by fr58386612** [lework/kainstall-offline#2]
cp: 无法获取"/tmp/kainstall.1xgFLhIca2/rpms/kubeadm/*" 的文件状态(stat): 没有那个文件或目录
[2022-02-18T16:22:45.196987829+0800]: ERROR:   [offline] scp kube file to 127.0.0.1 failed.

**Comment by fr58386612** [comment]
centos7的系统,使用的1.23.1的离线安装包

**Comment by lework** [comment]
这样看不出来问题，你要把log文件发上来。
